# Включаем правила линтинга
select = [
    "E", # Pycodestyle errors
    "F", # Pyflakes
    "I", # isort (сортировка импортов)
    "B", # flake8-bugbear
    "C", # flake8-comprehensions
    "W", # Pycodestyle warnings
]

# Игнорируем конкретные правила
ignore = [
    "E203", # Пробел перед двоеточием в срезах
    "E501", # Длина строки
    "B008", # Функция слишком длинная
    "F821", # Неопределенное имя внутри функции
]

# Настройка длины строки
line-length = 79

# Включаем форматирование (как Black) и настраиваем его
# Настройки форматирования
[format]
skip-magic-trailing-comma = true # Отключаем удаление лишних переносов строк
