services:
  fastdb:
    image: postgres:latest
    container_name: fastdb
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"

  # fastapi:
  #   build: .
  #   command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - fastdb
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   networks:
  #     - app-network


volumes:
  pgdata:

# networks:
#   app-network:
